#!/bin/bash

# check if AWS cLI is installed

if ! command -v aws &> /dev/null
then
        echo "AWS CLI NOT INSTALLED!"
        exit 1
fi

# check if file path is provided

if [ -z "$1" ]
then
        echo "Provide file path"
        exit 1
fi

# check if file exists

file_path="$1"
if [ ! -f $file_path ]
then
        echo "File does not exist"
        exit 1
fi
# Check if the required arguments are provided
if [ $# -ne 3 ]
then
    echo "Usage: $0 <bucket> <source_file> <destination_key>"
        exit 1
fi
# Assign command-line arguments to variables
        bucket="$1"
        source_file="$2"
        destination_key="$3"
# upload file to s3 bucket

error_file="error.txt"
 aws s3api put-object --bucket "$bucket" --key "$destination_key" --body "$source_file" 2> "$error_file"

# check exit status of the command

if [ $? -eq 0 ]
then
        echo "File successfully uploaded to S3 bucket : $bucket_name"
else
        echo "File upload unsuccessful"
        cat "$error_file"
        exit 1
fi
