#!/bin/bash

# Define the installation directory
install_dir="/usr/local/bin"

# Copy the main script to the installation directory
cp -f clouduploader "$install_dir/"

# Make the script executable
chmod +x "$install_dir/clouduploader"

echo "S3 clouduploader has been installed to $install_dir."
# To remove the installation script
rm -f "$0"
